### PR TITLE
Add option to define custom foreign keys for relations to delete

### PR DESCRIPTION
**Pull request by mahnuh**
I found this very useful when using polymorphic relations.

### CODE REVIEW

**Comment by mahnuh** [comment]
Hey @rocknrolla777 what do you think about this pr?

**Comment by rocknrolla777** [comment]
Looks good! Thank you, I'm going to make small changes and merge it to master branch

**Comment by mahnuh** [comment]
Great! Will you publish it to npm as well?

**Comment by rocknrolla777** [comment]
Yeah! Today!

**Comment by rocknrolla777** [comment]
@mahnuh IMPORTANT! Mixin object structure is changed. If you use "relationsConfig" key, please use 1.3.1 version
npm install --save loopback-cascade-delete-mixin@1.3.1 
or change object structure! (see below)

**Comment by mahnuh** [comment]
Thanks @rocknrolla777, working like charm!

**Pull request merged**
